### ISSUE TITLE
Add title image to README

### ISSUE THREAD

**Issue by castaneai** [Mitu217/tamate#136]
こういうのを

![image](https://user-images.githubusercontent.com/562795/43790305-2c35e798-9aad-11e8-895a-7d59025e9e07.png)

**Comment by Mitu217** [comment]
いただいた画像、mysqlの🐬の味がめっちゃあって好き

**Comment by Mitu217** [comment]
こんな感じでどうだろう。
ロゴは入れると、あとから面倒そうなのでやめておきたい

<img width="526" alt="2018-11-03 17 49 25" src="https://user-images.githubusercontent.com/3307063/47950092-eda37f80-df90-11e8-91be-6654d17dc98a.png">

**Comment by castaneai** [comment]
おお、！
矢印がなんかあちこちに向かってて一瞬わからんかったので、こういうのでどうですか？

![image](https://user-images.githubusercontent.com/562795/47955149-ac35c300-dfd6-11e8-874d-2ef541e0c797.png)

**Comment by Mitu217** [comment]
つい入れたくなってeikoと
<img width="726" alt="2018-11-04 9 42 44" src="https://user-images.githubusercontent.com/3307063/47958786-0ace6180-e016-11e8-8c03-553046edb1a3.png">

**Comment by castaneai** [comment]
LGTM 👍
