### ISSUE TITLE
Schema builder from database

### ISSUE THREAD

**Issue by castaneai** [Mitu217/tamate#15]
e.g. reading schema from `INFORMATION_SCHEMA` on MySQL

```go
sc, err := schema.NewFromMySQL(database.Server, "db_name.table_name")
```

**Comment by Mitu217** [comment]
Output schema.json


![2018-03-08 23 24 01](https://user-images.githubusercontent.com/3307063/37155911-e95818d0-2327-11e8-8b64-84f832126364.png)
