### ISSUE TITLE
SHOW COLUMNS depends on MySQL

### ISSUE THREAD

**Issue by castaneai** [Mitu217/tamate#44]
`SHOW COLUMNS ....` on SQLDataSource.GetSchema() depends on MySQL,

## e.g. SQLite 

```
PRAGMA table_info(table_name);
```

**Comment by castaneai** [comment]
GetSchema() は driver ごとに対応していくしかなさそう

**Comment by Mitu217** [comment]
driverごとにsql.goで対応していく感じで
