### ISSUE TITLE
DiffRow is imperfect

### ISSUE THREAD

**Issue by Mitu217** [Mitu217/tamate#55]
* Columnの順番がLeftとRightで同じ前提で組まれている
* SchemaのColumnIndexにもとづいて制御されるべき
  * そうしないとカラムの定義順番が異なるテーブル同士の比較をするときに詰む
  * 他にも考慮できていないケースが多数ありそう

**Comment by Mitu217** [comment]
下記のようなmap[string]stringでデータをRowごとに保存すれば良さそう？
```
Row {
  Values map[string]string
}
```

**Comment by Mitu217** [comment]
#88

**Comment by castaneai** [comment]
Closed by #93
