### ISSUE TITLE
No Gopkg.toml found.

### ISSUE THREAD

**Issue by katsew** [Mitu217/tamate#65]
dep ensure fails because Gopkg.toml exists.
Please add it.

**Comment by castaneai** [comment]
Fixed with https://github.com/Mitu217/tamate/commit/61846665ffd7680e6c004c1926c4aedf4347ce6a

**Comment by Mitu217** [comment]
Sorry. add Gopkg.toml and Gopkg.lock file

61846665ffd7680e6c004c1926c4aedf4347ce6a
