### ISSUE TITLE
Spanner datasource GetRows is missing value in some types.

### ISSUE THREAD

**Issue by katsew** [Mitu217/tamate#87]
I've tried `Array`, `Bool`, `Float64` but they had no value contained.

**Comment by katsew** [comment]
Maybe this should call `Value.Kind` before convert to string or find some way similar to it.
https://github.com/Mitu217/tamate/blob/master/datasource/spanner.go#L176

**Comment by katsew** [comment]
I haven't tested `Bytes` type, need to be tested.

**Comment by castaneai** [comment]
Closed by #93
